---
version: 2
registries:
  rubygems-github:
    type: rubygems-server
    url: https://rubygems.pkg.github.com/clio
    token: "${{ secrets.DEPENDABOT_GITHUB_TOKEN }}"
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 0
